export type M365PopupStringKey =
  | 'title'
  | 'overview'
  | 'conversation'
  | 'organize'
  | 'export'
  | 'sync'
  | 'appearance'
  | 'advanced'
  | 'enabled'
  | 'timeline'
  | 'chatWidth'
  | 'theme'
  | 'system'
  | 'light'
  | 'dark'
  | 'folders'
  | 'prompts'
  | 'starred'
  | 'activeCloud'
  | 'none'
  | 'openDockHint'
  | 'resetV2'
  | 'resetConfirm'
  | 'resetDone'
  | 'statusReady'
  | 'localOnly'
  | 'googleDrive'
  | 'oneDrive'
  | 'notConfigured';

type Dictionary = Record<M365PopupStringKey, string>;

const en: Dictionary = {
  title: 'Voyager for M365',
  overview: 'Overview',
  conversation: 'Conversation',
  organize: 'Organize',
  export: 'Export',
  sync: 'Sync',
  appearance: 'Appearance',
  advanced: 'Advanced',
  enabled: 'Enable M365 features',
  timeline: 'Enable timeline',
  chatWidth: 'Chat width',
  theme: 'Theme',
  system: 'System',
  light: 'Light',
  dark: 'Dark',
  folders: 'Folders',
  prompts: 'Prompts',
  starred: 'Starred',
  activeCloud: 'Primary cloud',
  none: 'None',
  openDockHint: 'Use VoyagerDock in M365 to manage messages, prompts, folders, and exports.',
  resetV2: 'Reset V2 data',
  resetConfirm: 'Reset Voyager V2 settings and workspace? Legacy data will remain untouched.',
  resetDone: 'V2 data reset',
  statusReady: 'M365 controls are ready',
  localOnly: 'Local only',
  googleDrive: 'Google Drive',
  oneDrive: 'OneDrive',
  notConfigured: 'Not configured',
};

const dictionaries: Record<string, Dictionary> = {
  en,
  zh: {
    ...en,
    title: 'Voyager M365 控制中心',
    overview: '概览',
    conversation: '会话',
    organize: '整理',
    export: '导出',
    sync: '同步',
    appearance: '外观',
    advanced: '高级',
    enabled: '启用 M365 功能',
    timeline: '启用时间轴',
    chatWidth: '聊天宽度',
    theme: '主题',
    system: '跟随系统',
    light: '浅色',
    dark: '深色',
    folders: '文件夹',
    prompts: '提示词',
    starred: '星标',
    activeCloud: '主云',
    none: '无',
    openDockHint: '请在 M365 页面使用 VoyagerDock 管理消息、提示词、文件夹和导出。',
    resetV2: '重置 V2 数据',
    resetConfirm: '确认重置 Voyager V2 设置和工作区？旧数据不会被删除。',
    resetDone: 'V2 数据已重置',
    statusReady: 'M365 控制已就绪',
    localOnly: '仅本地',
    googleDrive: 'Google Drive',
    oneDrive: 'OneDrive',
    notConfigured: '未配置',
  },
  zh_TW: {
    ...en,
    title: 'Voyager M365 控制中心',
    overview: '概覽',
    conversation: '對話',
    organize: '整理',
    export: '匯出',
    sync: '同步',
    appearance: '外觀',
    advanced: '進階',
    enabled: '啟用 M365 功能',
    timeline: '啟用時間軸',
    chatWidth: '聊天寬度',
    theme: '主題',
    system: '跟隨系統',
    light: '淺色',
    dark: '深色',
    folders: '資料夾',
    prompts: '提示詞',
    starred: '星號',
    activeCloud: '主要雲端',
    none: '無',
    openDockHint: '請在 M365 頁面使用 VoyagerDock 管理訊息、提示詞、資料夾與匯出。',
    resetV2: '重設 V2 資料',
    resetConfirm: '確定重設 Voyager V2 設定與工作區？舊資料不會刪除。',
    resetDone: 'V2 資料已重設',
    statusReady: 'M365 控制已就緒',
    localOnly: '僅本機',
    googleDrive: 'Google Drive',
    oneDrive: 'OneDrive',
    notConfigured: '未設定',
  },
  ja: {
    ...en,
    overview: '概要',
    conversation: '会話',
    organize: '整理',
    export: 'エクスポート',
    sync: '同期',
    appearance: '外観',
    advanced: '詳細',
    enabled: 'M365 機能を有効化',
    timeline: 'タイムラインを有効化',
    chatWidth: 'チャット幅',
    theme: 'テーマ',
    system: 'システム',
    light: 'ライト',
    dark: 'ダーク',
    folders: 'フォルダー',
    prompts: 'プロンプト',
    starred: 'スター',
    activeCloud: 'メインクラウド',
    none: 'なし',
    openDockHint:
      'M365 ページの VoyagerDock でメッセージ、プロンプト、フォルダー、エクスポートを管理します。',
    resetV2: 'V2 データをリセット',
    resetConfirm: 'Voyager V2 の設定とワークスペースをリセットしますか？旧データは削除されません。',
    resetDone: 'V2 データをリセットしました',
    statusReady: 'M365 コントロールの準備完了',
    localOnly: 'ローカルのみ',
    notConfigured: '未設定',
  },
  ko: {
    ...en,
    overview: '개요',
    conversation: '대화',
    organize: '정리',
    export: '내보내기',
    sync: '동기화',
    appearance: '모양',
    advanced: '고급',
    enabled: 'M365 기능 사용',
    timeline: '타임라인 사용',
    chatWidth: '채팅 너비',
    theme: '테마',
    system: '시스템',
    light: '라이트',
    dark: '다크',
    folders: '폴더',
    prompts: '프롬프트',
    starred: '별표',
    activeCloud: '기본 클라우드',
    none: '없음',
    openDockHint: 'M365 페이지의 VoyagerDock에서 메시지, 프롬프트, 폴더와 내보내기를 관리하세요.',
    resetV2: 'V2 데이터 초기화',
    resetConfirm: 'Voyager V2 설정과 작업 공간을 초기화할까요? 기존 데이터는 삭제되지 않습니다.',
    resetDone: 'V2 데이터 초기화됨',
    statusReady: 'M365 컨트롤 준비됨',
    localOnly: '로컬 전용',
    notConfigured: '구성되지 않음',
  },
  fr: {
    ...en,
    overview: 'Aperçu',
    conversation: 'Conversation',
    organize: 'Organiser',
    export: 'Exporter',
    sync: 'Synchroniser',
    appearance: 'Apparence',
    advanced: 'Avancé',
    enabled: 'Activer les fonctions M365',
    timeline: 'Activer la chronologie',
    chatWidth: 'Largeur du chat',
    theme: 'Thème',
    system: 'Système',
    light: 'Clair',
    dark: 'Sombre',
    folders: 'Dossiers',
    prompts: 'Prompts',
    starred: 'Favoris',
    activeCloud: 'Cloud principal',
    none: 'Aucun',
    openDockHint:
      'Utilisez VoyagerDock dans M365 pour gérer messages, prompts, dossiers et exports.',
    resetV2: 'Réinitialiser les données V2',
    resetConfirm:
      'Réinitialiser les réglages et l’espace V2 ? Les anciennes données seront conservées.',
    resetDone: 'Données V2 réinitialisées',
    statusReady: 'Contrôles M365 prêts',
    localOnly: 'Local uniquement',
    notConfigured: 'Non configuré',
  },
  es: {
    ...en,
    overview: 'Resumen',
    conversation: 'Conversación',
    organize: 'Organizar',
    export: 'Exportar',
    sync: 'Sincronizar',
    appearance: 'Apariencia',
    advanced: 'Avanzado',
    enabled: 'Activar funciones M365',
    timeline: 'Activar cronología',
    chatWidth: 'Ancho del chat',
    theme: 'Tema',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Oscuro',
    folders: 'Carpetas',
    prompts: 'Prompts',
    starred: 'Destacados',
    activeCloud: 'Nube principal',
    none: 'Ninguna',
    openDockHint:
      'Usa VoyagerDock en M365 para gestionar mensajes, prompts, carpetas y exportaciones.',
    resetV2: 'Restablecer datos V2',
    resetConfirm: '¿Restablecer ajustes y espacio V2? Los datos antiguos se conservarán.',
    resetDone: 'Datos V2 restablecidos',
    statusReady: 'Controles M365 listos',
    localOnly: 'Solo local',
    notConfigured: 'Sin configurar',
  },
  pt: {
    ...en,
    overview: 'Visão geral',
    conversation: 'Conversa',
    organize: 'Organizar',
    export: 'Exportar',
    sync: 'Sincronizar',
    appearance: 'Aparência',
    advanced: 'Avançado',
    enabled: 'Ativar recursos M365',
    timeline: 'Ativar linha do tempo',
    chatWidth: 'Largura do chat',
    theme: 'Tema',
    system: 'Sistema',
    light: 'Claro',
    dark: 'Escuro',
    folders: 'Pastas',
    prompts: 'Prompts',
    starred: 'Favoritos',
    activeCloud: 'Nuvem principal',
    none: 'Nenhuma',
    openDockHint:
      'Use o VoyagerDock no M365 para gerenciar mensagens, prompts, pastas e exportações.',
    resetV2: 'Redefinir dados V2',
    resetConfirm: 'Redefinir configurações e espaço V2? Os dados antigos serão preservados.',
    resetDone: 'Dados V2 redefinidos',
    statusReady: 'Controles M365 prontos',
    localOnly: 'Somente local',
    notConfigured: 'Não configurado',
  },
  ru: {
    ...en,
    overview: 'Обзор',
    conversation: 'Диалог',
    organize: 'Организация',
    export: 'Экспорт',
    sync: 'Синхронизация',
    appearance: 'Внешний вид',
    advanced: 'Дополнительно',
    enabled: 'Включить функции M365',
    timeline: 'Включить шкалу',
    chatWidth: 'Ширина чата',
    theme: 'Тема',
    system: 'Системная',
    light: 'Светлая',
    dark: 'Тёмная',
    folders: 'Папки',
    prompts: 'Промпты',
    starred: 'Избранное',
    activeCloud: 'Основное облако',
    none: 'Нет',
    openDockHint: 'Используйте VoyagerDock в M365 для сообщений, промптов, папок и экспорта.',
    resetV2: 'Сбросить данные V2',
    resetConfirm: 'Сбросить настройки и рабочую область V2? Старые данные останутся.',
    resetDone: 'Данные V2 сброшены',
    statusReady: 'Управление M365 готово',
    localOnly: 'Только локально',
    notConfigured: 'Не настроено',
  },
  ar: {
    ...en,
    overview: 'نظرة عامة',
    conversation: 'المحادثة',
    organize: 'تنظيم',
    export: 'تصدير',
    sync: 'مزامنة',
    appearance: 'المظهر',
    advanced: 'متقدم',
    enabled: 'تمكين ميزات M365',
    timeline: 'تمكين المخطط الزمني',
    chatWidth: 'عرض المحادثة',
    theme: 'السمة',
    system: 'النظام',
    light: 'فاتح',
    dark: 'داكن',
    folders: 'المجلدات',
    prompts: 'المطالبات',
    starred: 'المميزة',
    activeCloud: 'السحابة الأساسية',
    none: 'لا شيء',
    openDockHint: 'استخدم VoyagerDock داخل M365 لإدارة الرسائل والمطالبات والمجلدات والتصدير.',
    resetV2: 'إعادة ضبط بيانات V2',
    resetConfirm: 'إعادة ضبط إعدادات ومساحة V2؟ ستبقى البيانات القديمة دون حذف.',
    resetDone: 'تمت إعادة ضبط بيانات V2',
    statusReady: 'عناصر تحكم M365 جاهزة',
    localOnly: 'محلي فقط',
    notConfigured: 'غير مهيأ',
  },
};

export function getM365PopupStrings(language = navigator.language): Dictionary {
  const normalized = language.replace('-', '_');
  return dictionaries[normalized] ?? dictionaries[normalized.split('_')[0]] ?? en;
}
